### ISSUE TITLE
Application is still hard coded to find files in src...

### ISSUE THREAD

**Issue by eliotpearson** [cmsc495-fall2016/cmsc495-fall2016.github.io#18]
I moved jar to /tmp tried to recreate test data and received the following stacktrace.

[!] Begin ingestion of Recipe test_classes data.
java.io.FileNotFoundException: src/main/java/sharkbread/test/data/recipe_data_optionals_removed.csv (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileReader.<init>(FileReader.java:72)
    at sharkbread.test.classes.RecipeTest.populateTestData(RecipeTest.java:83)
    at sharkbread.test.classes.RecipeTest.main(RecipeTest.java:142)
    at sharkbread.test.classes.AllTest.createaAllData(AllTest.java:35)
    at sharkbread.test.classes.ui.CreateaAllDataRunner.run(CreateaAllDataRunner.java:26)
    at java.lang.Thread.run(Thread.java:745)
[!] Test data read in; attempting to write to table
[!] Deleting all prior recipe entries (we are in test mode!)
[!] If no stacktrace, assume db recipe table is populated.
[!] Begin ingestion of Ingredient test_classes data.
java.io.FileNotFoundException: src/main/java/sharkbread/test/data/ingredient_data.csv (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileReader.<init>(FileReader.java:72)
    at sharkbread.test.classes.IngredientTest.populateTestData(IngredientTest.java:42)
    at sharkbread.test.classes.IngredientTest.main(IngredientTest.java:84)
    at sharkbread.test.classes.AllTest.createaAllData(AllTest.java:36)
    at sharkbread.test.classes.ui.CreateaAllDataRunner.run(CreateaAllDataRunner.java:26)
    at java.lang.Thread.run(Thread.java:745)
[!] Test data read in; attempting to write to table
[!] Deleting all prior ingredient entries (we are in test mode!)
[!] If no stacktrace, assume db ingredient table is populated.
[!] Begin ingestion of User test_classes data.
java.io.FileNotFoundException: src/main/java/sharkbread/test/data/user_data.csv (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileReader.<init>(FileReader.java:72)
    at sharkbread.test.classes.UserTest.populateTestData(UserTest.java:43)
    at sharkbread.test.classes.UserTest.main(UserTest.java:85)
    at sharkbread.test.classes.AllTest.createaAllData(AllTest.java:37)
    at sharkbread.test.classes.ui.CreateaAllDataRunner.run(CreateaAllDataRunner.java:26)
    at java.lang.Thread.run(Thread.java:745)
[!] Test data read in; attempting to write to table
[!] Deleting all prior user entries (we are in test mode!)
[!] If no stacktrace, assume db user table is populated.
[!] Begin ingestion of Uses test_classes data.
java.io.FileNotFoundException: src/main/java/sharkbread/test/data/uses_data.csv (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileReader.<init>(FileReader.java:72)
    at sharkbread.test.classes.UsesTest.populateTestData(UsesTest.java:40)
    at sharkbread.test.classes.UsesTest.main(UsesTest.java:80)
    at sharkbread.test.classes.AllTest.createaAllData(AllTest.java:38)
    at sharkbread.test.classes.ui.CreateaAllDataRunner.run(CreateaAllDataRunner.java:26)
    at java.lang.Thread.run(Thread.java:745)
[!] Test data read in; attempting to write to table
[!] Deleting all prior uses entries (we are in test mode!)
## [!] If no stacktrace, assume db ingredient table is populated.

CreateAllData Thread Actions Complete

You can duplicate by going to Testing->Delete All Data->Create All Data.

![screen shot 2016-10-08 at 6 38 07 am](https://cloud.githubusercontent.com/assets/1199317/19212572/ec503d4e-8d21-11e6-997b-8051bc643dc1.png)

**Comment by ahowell82** [comment]
I guess we need to move the test data to the resources folder and parse from there to fix this

**Comment by eliotpearson** [comment]
This is resolved by commit https://github.com/cmsc495-fall2016/cmsc495-fall2016.github.io/commit/1eef842227666f448052279092eae7067ece354f.
